import Header from "./components/header";
import Produtos from "./produtos";

export const metadata = {
  title: "Capputeeno",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <Header/>
      <Produtos/>
    </>
  );
}
